data = {}
username = '张三'
password = '123'
age = '18'
sex = '男'
phone = '121313313'
adderss = '华中师范大学南湖校区'
touxiang = '/static/img/1.jpg'
breif = '我是一个大傻逼'
data['name'] = username
data['sex'] = sex
data['phone'] = phone
data['age'] = age
data['adderss'] = adderss
data['touxiang'] = touxiang
data['breif'] = breif
data['password'] = password

yaoyue = {}
yqz = '张三'
syz = 'lisa'
movie = '肖申克的救赎'
yytime = '8-20'
yaoyue['yqz'] = yqz
yaoyue['syz'] = syz
yaoyue['movie'] = movie
yaoyue['yytime'] = yytime

friend1 = ['zhangsan', '123']
friend2 = ['lisi', '321']
friend3 = ['wangwu', '666']
dic = {}
dic[1] = friend1
dic[2] = friend2
dic[3] = friend3
dic[4] = friend3
dic[5] = friend3
dic[6] = friend2
